package inventory

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseYarnLockV1(t *testing.T) {
	content := `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@babel/code-frame@^7.0.0":
  version "7.10.4"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.10.4.tgz"

lodash@^4.17.20, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://..."

minimist@^1.2.5:
  version "1.2.6"
`
	tmp := t.TempDir()
	path := filepath.Join(tmp, "yarn.lock")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	pkgs, err := parseYarnLock(path)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"@babel/code-frame": "7.10.4",
		"lodash":            "4.17.21",
		"minimist":          "1.2.6",
	}
	if len(pkgs) != len(want) {
		t.Fatalf("got %d packages, want %d: %+v", len(pkgs), len(want), pkgs)
	}
	for _, p := range pkgs {
		w, ok := want[p.Name]
		if !ok || p.Version != w {
			t.Errorf("unexpected %s@%s; want %v", p.Name, p.Version, want)
		}
	}
}

func TestParseYarnLockBerry(t *testing.T) {
	content := `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"@babel/code-frame@npm:^7.0.0":
  version: 7.10.4
  resolution: "@babel/code-frame@npm:7.10.4"

"lodash@npm:^4.17.20, lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
`
	tmp := t.TempDir()
	path := filepath.Join(tmp, "yarn.lock")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	pkgs, err := parseYarnLock(path)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"@babel/code-frame": "7.10.4",
		"lodash":            "4.17.21",
	}
	if len(pkgs) != len(want) {
		t.Fatalf("got %d packages, want %d: %+v", len(pkgs), len(want), pkgs)
	}
	for _, p := range pkgs {
		w, ok := want[p.Name]
		if !ok || p.Version != w {
			t.Errorf("unexpected %s@%s; want %v", p.Name, p.Version, want)
		}
	}
}

func TestParseYarnV1Keys(t *testing.T) {
	cases := []struct {
		in   string
		want []string
	}{
		{`lodash@^4.17.20`, []string{"lodash@^4.17.20"}},
		{`lodash@^4.17.20, lodash@^4.17.21`, []string{"lodash@^4.17.20", "lodash@^4.17.21"}},
		{`"@babel/code-frame@^7.0.0"`, []string{"@babel/code-frame@^7.0.0"}},
		{`"@scope/a@^1.0.0", "@scope/a@^1.2.0"`, []string{"@scope/a@^1.0.0", "@scope/a@^1.2.0"}},
	}
	for _, c := range cases {
		got := parseYarnV1Keys(c.in)
		if len(got) != len(c.want) {
			t.Errorf("%q → %v, want %v", c.in, got, c.want)
			continue
		}
		for i := range got {
			if got[i] != c.want[i] {
				t.Errorf("%q[%d] = %q, want %q", c.in, i, got[i], c.want[i])
			}
		}
	}
}
