package inventory

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseYarnLockV1(t *testing.T) {
	content := `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@babel/code-frame@^7.0.0":
  version "7.10.4"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.10.4.tgz"

lodash@^4.17.20, lodash@^4.17.21:
  version "4.17.21"
  resolved "https://..."

minimist@^1.2.5:
  version "1.2.6"
`
	tmp := t.TempDir()
	path := filepath.Join(tmp, "yarn.lock")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	pkgs, err := parseYarnLock(path)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"@babel/code-frame": "7.10.4",
		"lodash":            "4.17.21",
		"minimist":          "1.2.6",
	}
	if len(pkgs) != len(want) {
		t.Fatalf("got %d packages, want %d: %+v", len(pkgs), len(want), pkgs)
	}
	for _, p := range pkgs {
		w, ok := want[p.Name]
		if !ok || p.Version != w {
			t.Errorf("unexpected %s@%s; want %v", p.Name, p.Version, want)
		}
	}
}

func TestParseYarnLockBerry(t *testing.T) {
	content := `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"@babel/code-frame@npm:^7.0.0":
  version: 7.10.4
  resolution: "@babel/code-frame@npm:7.10.4"

"lodash@npm:^4.17.20, lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
`
	tmp := t.TempDir()
	path := filepath.Join(tmp, "yarn.lock")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	pkgs, err := parseYarnLock(path)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"@babel/code-frame": "7.10.4",
		"lodash":            "4.17.21",
	}
	if len(pkgs) != len(want) {
		t.Fatalf("got %d packages, want %d: %+v", len(pkgs), len(want), pkgs)
	}
	for _, p := range pkgs {
		w, ok := want[p.Name]
		if !ok || p.Version != w {
			t.Errorf("unexpected %s@%s; want %v", p.Name, p.Version, want)
		}
	}
}

// TestParseYarnLockAlias verifies the npm-alias target is captured into
// AliasOf for both lockfile formats, while plain deps leave it empty.
// This is what lets the integrity name-drift check tell a legitimate
// alias (string-width-cjs → string-width) apart from a directory swap.
func TestParseYarnLockAlias(t *testing.T) {
	v1 := `# yarn lockfile v1

string-width-cjs@npm:string-width@^4.2.0:
  version "4.2.3"
  resolved "https://registry.yarnpkg.com/string-width/-/string-width-4.2.3.tgz"

lodash@^4.17.21:
  version "4.17.21"
`
	berry := `__metadata:
  version: 6

"string-width-cjs@npm:string-width@^4.2.0":
  version: 4.2.3
  resolution: "string-width@npm:4.2.3"

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
`
	for _, tc := range []struct{ name, content string }{{"v1", v1}, {"berry", berry}} {
		t.Run(tc.name, func(t *testing.T) {
			tmp := t.TempDir()
			path := filepath.Join(tmp, "yarn.lock")
			if err := os.WriteFile(path, []byte(tc.content), 0644); err != nil {
				t.Fatal(err)
			}
			pkgs, err := parseYarnLock(path)
			if err != nil {
				t.Fatal(err)
			}
			var alias, plain *Package
			for i := range pkgs {
				switch pkgs[i].Name {
				case "string-width-cjs":
					alias = &pkgs[i]
				case "lodash":
					plain = &pkgs[i]
				}
			}
			if alias == nil {
				t.Fatalf("missing aliased entry string-width-cjs in %+v", pkgs)
			}
			if alias.AliasOf != "string-width" {
				t.Errorf("AliasOf = %q, want %q", alias.AliasOf, "string-width")
			}
			if plain == nil || plain.AliasOf != "" {
				t.Errorf("plain dep must have empty AliasOf, got %+v", plain)
			}
		})
	}
}

func TestParseYarnV1Keys(t *testing.T) {
	cases := []struct {
		in   string
		want []string
	}{
		{`lodash@^4.17.20`, []string{"lodash@^4.17.20"}},
		{`lodash@^4.17.20, lodash@^4.17.21`, []string{"lodash@^4.17.20", "lodash@^4.17.21"}},
		{`"@babel/code-frame@^7.0.0"`, []string{"@babel/code-frame@^7.0.0"}},
		{`"@scope/a@^1.0.0", "@scope/a@^1.2.0"`, []string{"@scope/a@^1.0.0", "@scope/a@^1.2.0"}},
	}
	for _, c := range cases {
		got := parseYarnV1Keys(c.in)
		if len(got) != len(c.want) {
			t.Errorf("%q → %v, want %v", c.in, got, c.want)
			continue
		}
		for i := range got {
			if got[i] != c.want[i] {
				t.Errorf("%q[%d] = %q, want %q", c.in, i, got[i], c.want[i])
			}
		}
	}
}
