package gate

import (
	"testing"
)

func TestParseYarnClassicLock(t *testing.T) {
	body := []byte(`# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"@my-org/utils@^1.0.0":
  version "1.0.5"
  resolved "https://registry.yarnpkg.com/@my-org/utils/-/utils-1.0.5.tgz"

react@^18.0.0, react@^18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"
`)
	refs, err := parseYarnClassicLock(body, []string{"lodash@^4.17.21"})
	if err != nil {
		t.Fatal(err)
	}
	if len(refs) != 3 {
		t.Errorf("expected 3 refs, got %d: %v", len(refs), refs)
	}
	byID := map[string]PackageRef{}
	for _, r := range refs {
		byID[r.String()] = r
	}
	if r, ok := byID["npm:lodash@4.17.21"]; !ok || !r.Direct {
		t.Errorf("lodash@4.17.21 missing or not Direct: %v", refs)
	}
	if _, ok := byID["npm:@my-org/utils@1.0.5"]; !ok {
		t.Errorf("@my-org/utils@1.0.5 missing: %v", refs)
	}
	if _, ok := byID["npm:react@18.2.0"]; !ok {
		t.Errorf("react@18.2.0 missing: %v", refs)
	}
}

func TestParsePnpmKey(t *testing.T) {
	cases := []struct {
		in              string
		wantName, wantV string
	}{
		// v7+ forms
		{"/lodash@4.17.21", "lodash", "4.17.21"},
		{"/@scope/pkg@1.0.0", "@scope/pkg", "1.0.0"},
		{"lodash@4.17.21", "lodash", "4.17.21"},
		// v5-6 forms
		{"/lodash/4.17.21", "lodash", "4.17.21"},
		{"/@scope/pkg/1.0.0", "@scope/pkg", "1.0.0"},
		// v7+ with peer-deps suffix
		{"/foo@1.2.3 (react@18)", "foo", "1.2.3"},
	}
	for _, c := range cases {
		gotN, gotV := parsePnpmKey(c.in)
		if gotN != c.wantName || gotV != c.wantV {
			t.Errorf("parsePnpmKey(%q) = (%q,%q), want (%q,%q)",
				c.in, gotN, gotV, c.wantName, c.wantV)
		}
	}
}

func TestYarnBerryName(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"lodash@npm:^4.17.21", "lodash"},
		{"@scope/pkg@npm:1.0.0", "@scope/pkg"},
		{"react@npm:18.0.0, react@npm:18.2.0", "react"},
	}
	for _, c := range cases {
		// yarnBerryName operates on the FIRST comma-separated
		// part; the parser strips the comma upstream. Match
		// that contract here.
		spec := c.in
		if i := indexOfRune(spec, ','); i >= 0 {
			spec = spec[:i]
		}
		if got := yarnBerryName(spec); got != c.want {
			t.Errorf("yarnBerryName(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func indexOfRune(s string, r rune) int {
	for i, c := range s {
		if c == r {
			return i
		}
	}
	return -1
}
